language: r
r:
  - release
  - devel

cache: packages
sudo: required

script:
    - Rscript -e 'devtools::install_github("HJ08003/eco", force = TRUE)'
    - Rscript test.R

notifications:
  email:
    on_success: change
    on_failure: change
